apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp-pod-service
spec:
  containers:
  - name: webapp-pod
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5-arm64
