apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp-pod-service
    release: "0-5"
spec:
  containers:
  - name: webapp-pod
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5-arm64

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod-0
  labels:
    app: webapp-pod-service
    release: "0"
spec:
  containers:
  - name: webapp-pod-0
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-arm64
