apiVersion: v1
kind: Service
metadata:
  name: kunal-webapp
spec:
  # This defines which pods are going to be represented by this Service.
  # The Service becomes a network endpoint for either other services or
  # maybe external users to connect to (eg Browser).
  selector:
    app: webapp-pod-service
    release: "0"

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort